# Generated by Django 2.2.1 on 2020-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0002_auto_20200223_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_confirmed',
            new_name='tel_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='vcode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
