# Generated by Django 2.2.1 on 2020-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0003_auto_20200223_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_user', models.CharField(max_length=4)),
            ],
        ),
    ]
