# Generated by Django 2.2.1 on 2020-03-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0005_verif_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='csv',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
