# Generated by Django 2.2.1 on 2020-03-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0007_groupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='csv',
            new_name='groupe',
        ),
    ]
