# Generated by Django 2.2.1 on 2020-03-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0008_auto_20200320_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
