# Generated by Django 2.2.1 on 2020-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0011_auto_20200320_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='groupe',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
