# Generated by Django 2.2.1 on 2020-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0012_groupe_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numeros', models.CharField(max_length=80000)),
            ],
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
